### ISSUE TITLE
Chapter 1 spelling errors in definitions.jpg

### ISSUE THREAD

**Issue by RonTilby** [cfsamson/book-exploring-async-basics#17]
In chapter 1 the .jpg titled "Multitasking two tasks" 
https://cfsamson.github.io/book-exploring-async-basics/images/definitions.jpg
has some spelling errors:
paralleizing should be parallelizing
nececcarily should be necessarily
paralellizable should be parallelizable

**Comment by cfsamson** [comment]
Thanks for noticing that. I've corrected it but it seems that github pages has cached the image so it might take some time before it's actually visible.
