### ISSUE TITLE
Why process file system operation with threadpool?

### ISSUE THREAD

**Issue by sianhou1987** [cfsamson/book-exploring-async-basics#23]
In chapter 8.5, there are two reasons:

The reason for doing file I/O in the thread pool is complex, but the main takeaway is that due to how files are cached and how the hard drive works, most often the file I/O will be Ready almost immediately, so waiting for that in a event queue has very little effect in practice.

The second reason is that while Windows do have a completion based model, Linux and Macos doesn't. Reading a file into a buffer which your process controls can take some time, and if we do that in our main loop it will block a little bit which we really try to avoid.

Could someone provide me with mode details, such as some docs or article?

**Comment by cfsamson** [comment]
Hi.

I went a bit more in detail in chapter 9.1 and I think it answers all your questions:

> You might be wondering why we (and libuv and Rusts own tokio) do file operations in the threadpool and not in our epoll-event-queue? It's I/O isn't it?
> 
> There are actually several reasons for this:
> 
> First and foremost. The OS will cache a lot of files that are frequently accessed, and when the data is cached it will be available immediately. There is no real I/O in such a case. In addition, it seems that most programs tend to access the same files over and over so a cache hit will often be the case. Think of a web server for example, there's often a very limited amount of data accessed on disk.
> 
> Now if we say that data is cached most of the time, so it's readily available, it can be more expensive to actually register an event with the epoll-event-queue - get an immediate notification that the event is Ready and then perform the read. It might actually be faster to just read it in a blocking manner right away.
> 
> However, in our design the file will be read on our main thread, which means that if it's a large file it will still take some time to read it from the OS cache to your process memory (your buffer) and that will block our entire event loop.
> 
> Better do that in the thread pool.
> 
> Secondly, the support for async file operations is limited and to a varying degree well implemented. The only system that does this pretty good is Windows since it uses a completion based model (which means it can let you know when the data is read into your buffer).
> 
> It makes sense for a completion based model to try to do this asynchronously, but since the real effect are so small and the code complexity is high (especially when you're writing a server that is cross platform) most implementations find that using a thread pool gives good enough performance.
> 
> To sum i all up:
> 
> **Threadpool:**
> 
> Less code complexity
> Good performance
> Very little penalty in most use cases (like web servers)
> Synchronous file operations are well optimized on most platforms
>
>
> **Async file I/O:**
> 
> Increased code complexity
> Poor and limited APIs (Linux and Macos has different limitations)
> Weak platform support (does not work very well with a readiness based model)
> Little to no real gain for most use cases
>

As i also linked to in that chapter [I find this article useful](https://blog.libtorrent.org/2012/10/asynchronous-disk-io/) if you want to go more in depth on this subject.

**Comment by sianhou1987** [comment]
Thank you very much. I'm learning the details of async and I love your books very much.

**Comment by cfsamson** [comment]
No problem. Good luck on exploring concurrent programming!
