### ISSUE TITLE
Linux ASM-Write example is broken

### ISSUE THREAD

**Issue by Michael-J-Ward** [cfsamson/book-exploring-async-basics#24]
The Linux ASM-Write example doesn't print out the full message. It only prints out `H` and then stops. I believe there is an issue with passing in the length of the string, because hardcoding the length properly prints out the  message.

Broken example from text: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c8aa06a7a8357cf986d91dded9fa567b

Hardcoded length that works: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2237f8e6cbce2157ee04bcc5ccdc853d

Also- just want to take this opportunity to say thanks for these amazing resources that you've put together. Do you have a patreon or can I sponsor you through github or anything?

**Comment by cfsamson** [comment]
Thanks for catching this, and thanks for the feedback. It means a lot. I don't have pateron or anything like that at the moment, but it's really nice to get some positive comments now and them from others that find it useful.

I was pretty sure I tested all the code on linux on WLS and on the playground, but somehow I must have missed this. It seems like a fix is to pass in a pointer to the length and dereference that in ASM, however in theory, it should work as written as well but I'll have to dig a bit more to figure out what hapens here.

Link to fix: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dc60ce654d91f42748069c08273d109b

**Comment by cfsamson** [comment]
Ha, ok so i figured it out. Seems like there was a change in nightly at some point between me writing the book and now that results in rustc relying to one of the registers we write to. 

Now, passing in a pointer as above is only a workaround, the real fix is to clobber the registers we write to so the compiler knows we write to them:

```rust
#![feature(asm)]
fn main() {
    let message = String::from("Hello world from interrupt!\n");
    syscall(message);
}

#[cfg(target_os = "linux")]
#[inline(never)]
fn syscall(message: String) {
    let msg_ptr = message.as_ptr();
    let len = message.len();
    
    unsafe {
        asm!("
        mov     $$1, %rax  # system call 1 is write on linux
        mov     $$1, %rdi  # file handle 1 is stdout
        mov     $0, %rsi   # address of string to output
        mov     $1, %rdx   # number of bytes
        syscall            # call kernel, syscall interrupt
    "
        :
        : "r"(msg_ptr), "r"(len)
        : "rax", "rdi", "rsi", "rdx"
        )
    }
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=eec662a5aac69e64b29c75d4a115eb92

Now it works correctly in both debug and --release.

I'll update the book with this.
