### ISSUE TITLE
epoll vs kqueue link is dead

### ISSUE THREAD

**Issue by Michael-J-Ward** [cfsamson/book-exploring-async-basics#25]
The link in chapter 6 is dead

> We will not cover methods like `poll` and `select`, but I have an [article for you
> here](https://people.eecs.berkeley.edu/~sangjin/2012/12/21/epoll-vs-kqueue.html)
> if you want to learn a bit about these methods and how they differ from `epoll`.

I was going to open a pull request, but wasn't sure if you wanted to link to the wayback machine or to another website

* [article on wayback machine](http://web.archive.org/web/20190112082733/https://people.eecs.berkeley.edu/~sangjin/2012/12/21/epoll-vs-kqueue.html)

If this is too trivial to ping you about, let me know.

**Comment by cfsamson** [comment]
Not at all. I appreciate getting fixes like this so no worries. I think the wayback machine will have to do since I can't find another resource for it right now and the article was pretty good. I'll update the link :)
