### ISSUE TITLE
the book in github.io needs to be updated

### ISSUE THREAD

**Issue by Johnny4Fun** [cfsamson/book-exploring-async-basics#35]
![image](https://user-images.githubusercontent.com/10000619/83227301-6b079400-a1b6-11ea-9e5e-687a3eb0f0f2.png)
I found The code in [Chapter 8.2 ](https://cfsamson.github.io/book-exploring-async-basics/8_1_the_main_loop.html)is weird and I searched  the git log but found no record about it. Maybe you need to re-render the page and update it.
The main fn here looks sooo confusing.

**Comment by cfsamson** [comment]
This is strange. There must be something wrong so the hasn't rendered properly. I tried to clean the output dirs of mdbook and re-render it now and I think it's fixed.

The main fn there isn't supposed at all.

**Comment by Johnny4Fun** [comment]
Okay, it seems alright now.
