### ISSUE TITLE
Identation style

### ISSUE THREAD

**Issue by adrian5** [cfsamson/book-exploring-async-basics#51]
I'm currently reading this great introduction and ran into some unusual indentation.

From [3.1 Communicating with the operating system](https://github.com/cfsamson/book-exploring-async-basics/blob/master/src/3_1_communicating_with_the_os.md):

```rust
unsafe {
    llvm_asm!("
    mov     $$1, %rax   # system call 1 is write on linux
    mov     $$1, %rdi   # file handle 1 is stdout
    mov     $0, %rsi    # address of string to output
    mov     $1, %rdx    # number of bytes
    syscall             # call kernel, syscall interrupt
"   // ←
    :
    : "r"(msg_ptr), "r"(len)
    : "rax", "rdi", "rsi", "rdx"
    )

let mut output: u32 = 0;
    // ↓ whole block indented
    let handle = unsafe { GetStdHandle(-11) };
    if handle  == -1 {   // ←
        return Err(io::Error::last_os_error())
    }

    let res = unsafe {
        WriteConsoleW(handle, msg_ptr, len, &mut output, std::ptr::null())
        };   // ←
    if res  == 0 {   // ←
        return Err(io::Error::last_os_error());
    }
```

This looks somewhat deliberate, and I can see why it might make semantic sense, so I thought I'd ask before filing any PR to change those. Don't want to get into bikeshedding, so if it's deliberate, just close the issue.

**Comment by cfsamson** [comment]
Thanks :) 

I believe the indentation is the result of running rustfmt on the code (so maybe semi-deliberate) but if you think there is a better way to format it feel free to suggest that in a PR and I’ll take a look at it.

**Comment by adrian5** [comment]
The asm section indeed appears to be rustfmt's choice, but I don't think the other parts are (unless non-defaults were used). Since the style appears to follow throughout the book, I don't feel I should put my own stamp on it as a reader.

**Comment by cfsamson** [comment]
Sounds good. I’ll try to remember this if/when I update to the new rust inline asm syntax.
