### ISSUE TITLE
Nitpicky English correction in intro

### ISSUE THREAD

**Issue by L0uisc** [cfsamson/book-exploring-async-basics#53]
This issue is extremely nitpicky, but in the second point in the disclaimer in the intro:

We'll not primarily focus on code quality and safety **>,** though this is important, I will focus on understanding the concepts and ideas behind the code. We will have to make many shortcuts to keep this concise and short.

the highlighted comma should be either a dash or a semicolon.

**Comment by cfsamson** [comment]
Thanks for pointing that out. I re-worded it since the sentence was too long anyway.

Happy new year!

**Comment by L0uisc** [comment]
Thanks! Happy new year to you too!
